plugins {
    id 'java-library'
    id 'kotlin'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        jvmTarget = "1.8"
        freeCompilerArgs += '-opt-in=kotlin.RequiresOptIn'
    }
}

dependencies {
    api('org.ergoplatform:ergo-appkit_2.11:5.0.3') {
        exclude group: 'org.bouncycastle', module: 'bcprov-jdk15on'
    }

    api "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:$coroutines_version"
    api "com.github.MrStahlfelge.mosaik:common-runtime:$mosaik_version"
    api "com.github.MrStahlfelge.mosaik:clientconnector-okhttp:$mosaik_version"
    
    testImplementation "junit:junit:$junit_version"
    testImplementation "org.mockito.kotlin:mockito-kotlin:$mockito_version"
    testImplementation "com.squareup.okhttp3:mockwebserver:3.12.0"
}