name: Releases

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup Android build environment
        uses: android-actions/setup-android@v2.0.2
      - name: Generate debug keystore
        run: keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"
      - name: Move debug keystore
        run: mkdir ~/.android
      - name: Move debug keystore
        run: mv debug.keystore ~/.android/debug.keystore
      - name: Build Android debug apks
        run: ./gradlew clean android:assembleDebug
      - name: Release mainnet artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: android/build/outputs/apk/ergomainnet/debug/android-ergomainnet-debug.apk
          asset_name: ergowallet-mainnet-debug.apk
          asset_content_type: application/zip
      - name: Release testnet artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: android/build/outputs/apk/ergotestnet/debug/android-ergotestnet-debug.apk
          asset_name: ergowallet-testnet-debug.apk
          asset_content_type: application/zip
